# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='zmq_transport.common',
  serialized_pb='\n\rmessage.proto\x12\x14zmq_transport.common\"\r\n\x0bPingRequest\"\x1f\n\x10SubscribeRequest\x12\x0b\n\x03key\x18\x01 \x02(\t\"!\n\x12UnsubscribeRequest\x12\x0b\n\x03key\x18\x01 \x02(\t\"\xff\x01\n\rSourceRequest\x12\x1a\n\x12source_replica_uid\x18\x01 \x02(\t\x12!\n\x19source_replica_generation\x18\x02 \x02(\t\x12\x1f\n\x17source_replica_trans_id\x18\x03 \x02(\t\x12,\n$target_replica_last_known_generation\x18\x04 \x02(\t\x12*\n\"target_replica_last_known_trans_id\x18\x05 \x02(\t\x12\x0e\n\x06\x64oc_id\x18\x06 \x02(\t\x12\x0f\n\x07\x64oc_rev\x18\x07 \x02(\t\x12\x13\n\x0b\x64oc_content\x18\x08 \x02(\t\"p\n\x0eTargetResponse\x12\x1a\n\x12target_replica_uid\x18\x01 \x02(\t\x12!\n\x19target_replica_generation\x18\x02 \x02(\t\x12\x1f\n\x17target_replica_trans_id\x18\x03 \x02(\t\"\x1e\n\x0fPublisherUpdate\x12\x0b\n\x03key\x18\x01 \x02(\t')




_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='zmq_transport.common.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=52,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='zmq_transport.common.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='zmq_transport.common.SubscribeRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=54,
  serialized_end=85,
)


_UNSUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='UnsubscribeRequest',
  full_name='zmq_transport.common.UnsubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='zmq_transport.common.UnsubscribeRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=87,
  serialized_end=120,
)


_SOURCEREQUEST = _descriptor.Descriptor(
  name='SourceRequest',
  full_name='zmq_transport.common.SourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_replica_uid', full_name='zmq_transport.common.SourceRequest.source_replica_uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_replica_generation', full_name='zmq_transport.common.SourceRequest.source_replica_generation', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source_replica_trans_id', full_name='zmq_transport.common.SourceRequest.source_replica_trans_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_replica_last_known_generation', full_name='zmq_transport.common.SourceRequest.target_replica_last_known_generation', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_replica_last_known_trans_id', full_name='zmq_transport.common.SourceRequest.target_replica_last_known_trans_id', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc_id', full_name='zmq_transport.common.SourceRequest.doc_id', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc_rev', full_name='zmq_transport.common.SourceRequest.doc_rev', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doc_content', full_name='zmq_transport.common.SourceRequest.doc_content', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=378,
)


_TARGETRESPONSE = _descriptor.Descriptor(
  name='TargetResponse',
  full_name='zmq_transport.common.TargetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_replica_uid', full_name='zmq_transport.common.TargetResponse.target_replica_uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_replica_generation', full_name='zmq_transport.common.TargetResponse.target_replica_generation', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_replica_trans_id', full_name='zmq_transport.common.TargetResponse.target_replica_trans_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=380,
  serialized_end=492,
)


_PUBLISHERUPDATE = _descriptor.Descriptor(
  name='PublisherUpdate',
  full_name='zmq_transport.common.PublisherUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='zmq_transport.common.PublisherUpdate.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=494,
  serialized_end=524,
)

DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['UnsubscribeRequest'] = _UNSUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['SourceRequest'] = _SOURCEREQUEST
DESCRIPTOR.message_types_by_name['TargetResponse'] = _TARGETRESPONSE
DESCRIPTOR.message_types_by_name['PublisherUpdate'] = _PUBLISHERUPDATE

class PingRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PINGREQUEST

  # @@protoc_insertion_point(class_scope:zmq_transport.common.PingRequest)

class SubscribeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIBEREQUEST

  # @@protoc_insertion_point(class_scope:zmq_transport.common.SubscribeRequest)

class UnsubscribeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNSUBSCRIBEREQUEST

  # @@protoc_insertion_point(class_scope:zmq_transport.common.UnsubscribeRequest)

class SourceRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SOURCEREQUEST

  # @@protoc_insertion_point(class_scope:zmq_transport.common.SourceRequest)

class TargetResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TARGETRESPONSE

  # @@protoc_insertion_point(class_scope:zmq_transport.common.TargetResponse)

class PublisherUpdate(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PUBLISHERUPDATE

  # @@protoc_insertion_point(class_scope:zmq_transport.common.PublisherUpdate)


# @@protoc_insertion_point(module_scope)
