"""
Project Settings
"""

# Server Settings

SERVER_IP = "tcp://127.0.0.1"

PORT_APPLICATION_HANDLER = "6665"
PORT_CLIENT_HANDLER = "6666"
PORT_PUBLISHER = "6667"

ENDPOINT_APPLICATION_HANDLER = "%s:%s" % (SERVER_IP, PORT_APPLICATION_HANDLER)
ENDPOINT_CLIENT_HANDLER = "%s:%s" % (SERVER_IP, PORT_CLIENT_HANDLER)
ENDPOINT_PUBLISHER = "%s:%s" % (SERVER_IP, PORT_PUBLISHER)

# Application Settings
PORT_SERVER_HANDLER = "6664"
ENDPOINT_SERVER_HANDLER = "%s:%s" % (SERVER_IP, PORT_SERVER_HANDLER)

